---
author: "Simon Garnier"
title: "1 - Installing trackR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{1 - Installing trackR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Installing [`trackR`](https://github.com/swarm-lab/trackR) should go 
smoothly on all major operating systems (Mac, Windows, "Ubuntu-like" Linux). 
There are a few steps to follow before installing the package itself in order to
install all the necessary dependencies. 

All installation steps are described below. 

---

+ [1 - Installing `OpenCV`](#installing-opencv)
+ [2 - Installing `trackR`](#installing-trackr)

---

## 1 - Installing `OpenCV`

`trackR` uses the powerful computer-vision library [`OpenCV`](https://www.opencv.org) 
in order to load and process videos and images. Installing `OpenCV` can be a 
daunting task if you are not used to compiling complex software from source. 
For this reason, we have created [`ROpenCVLite`](https://CRAN.R-project.org/package=ROpenCVLite), 
a helper `R` package that will take care of this process for you.

Please go to [https://swarm-lab.github.io/ROpenCVLite/articles/install.html](https://swarm-lab.github.io/ROpenCVLite/articles/install.html) 
and follow the instructions there to install `OpenCV` on your system. There are 
slight differences between the installation processes for Mac, Windows, and 
Linux, so make sure to follow those that are for your operating system. The 
installation process should be straightforward (just a few buttons or links to 
click here and there) but the compilation of OpenCV will take some time (10 to 
20 minutes depending on your machine and operating system). Make yourself a nice 
cup of tea or coffee and relax in the meantime. 

Once you have installed `OpenCV` via `ROpenCVLite`, you can follow the rest of 
the installation instructions for `trackR` below. 

---

## 2 - Installing `trackR`

Once `OpenCV` is ready, you can install `trackR` and the rest of its dependencies 
by simply typing the following command in your R console: 

```r
remotes::install_github("swarm-lab/trackR")
```

---

You are now ready to proceed to the rest of the tutorials! 

+ [2 - Preparing videos (optional)](https://swarm-lab.github.io/trackR/articles/z2_videoFixer.html)
+ [3 - Tracking videos](https://swarm-lab.github.io/trackR/articles/z3_trackR.html)
+ [4 - Inspect and fix tracking results](https://swarm-lab.github.io/trackR/articles/z4_trackFixer.html)
+ [5 - Export tracking results as video](https://swarm-lab.github.io/trackR/articles/z4_trackPlayer.html)
